### ISSUE TITLE
Downloads 3rd party resources unnecessarily

### ISSUE THREAD

**Issue by sebbASF** [Humbedooh/asfmm#15]
The browser has to download 3rd party resources (e.g. fonts) for the app to operate.
This is unnecessary and reveals usage patterns.

**Comment by Humbedooh** [comment]
Addressed by removing the reliance on the web fonts in [2277b69](https://github.com/Humbedooh/asfmm/commit/2277b69a712fbe6d6872b2609ba984c254d341fb)
