### ISSUE TITLE
Need a log of proxy assignments (and rejected attempts)

### ISSUE THREAD

**Issue by tdunning** [Humbedooh/asfmm#28]
I tried pasting in 36 IDs as proxies. The experience was generally good.

I got a dialog that said 25 IDs were accepted and 11 were rejected as invalid or already having proxies. That's nice.

But when I download the logs, I don't see a history of what happened. What I would want to see is an entry that tdunning tried to register these 36 IDs, these 25 were accepted and these 11 were rejected. I would also hope to see a log entry for each ID that said that the ID was accepted or rejected with a reason for rejection.

All such log entries should be time-stamped, of course.

**Comment by Humbedooh** [comment]
This has been addressed in https://github.com/Humbedooh/asfmm/commit/ad7ab79f74308d06518dd3626a8b42ca770da011
